---
title: "Unión de capas rasterizadas"
format: 
  html:
    lang: es
    theme: cosmo
    toc: true
    toc-expand: 3
---

# Introducción
Este documento computacional une capas raster.

```{r}
#| label: carga-paquetes
#| message: false
#| code-fold: show
#| code-summary: "Código para la carga de paquetes"
 

# Paquetes
library(here)
library(terra)
```

# Parámetros generales

```{r}
#| label: parametros-generales
#| code-fold: show
#| code-summary: "Código para la definición de parámetros generales"


# Directorio de capas rasterizadas
DIRECTORIO_CAPAS_RASTERIZADAS <- 
  here("datos", "procesados", "rasterizados")

# Archivo raster de áreas silvestres protegidas (ASP)
ARCHIVO_RASTER_ASP <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "areas-silvestres-protegidas.tif")

# Archivo raster de patrimonio natural del estado (PNE)
ARCHIVO_RASTER_PNE <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "patrimonio-natural-estado.tif")

# Archivo raster de registro nacional de humedales (RNH)
ARCHIVO_RASTER_RNH <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "registro-nacional-humedales.tif")

# Archivo raster de cultivos
ARCHIVO_RASTER_CULTIVOS <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivos-2017.tif")

# Archivo raster de cultivo de piña
ARCHIVO_RASTER_PINA <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivo-pina-2019.tif")

# Archivo raster de cultivo de palma
ARCHIVO_RASTER_PALMA <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivo-palma-2019.tif")

# Archivo raster de pastos
ARCHIVO_RASTER_PASTOS <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivo-pastos-2019-2020.tif")

# Archivo raster de café 2017-2018
ARCHIVO_RASTER_CAFE <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivo-cafe-2017-2018.tif")

# Archivo raster de banano
ARCHIVO_RASTER_BANANO <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "fincas_Bananeras.tif")

# Archivo raster de caña 2020
ARCHIVO_RASTER_CANA_2020 <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "cultivo-cana-2020.tif")

# Archivo raster de cobertura forestal
ARCHIVO_RASTER_COBERTURA_FORESTAL <- 
  here(DIRECTORIO_CAPAS_RASTERIZADAS, "Cobertura forestal 2021.tif")

# Archivo raster de capa de uso agropecuario y bosques
ARCHIVO_RASTER_USO_AGROPECUARIO_BOSQUES <-
  here("salidas", "uso-agropecuario-bosques-2020.tif")
```

# Procesamiento

```{r}
#| label: union-capas-raster
#| code-fold: show
#| code-summary: "Código para la unión de capas raster"


# 1 CULTIVOS
# Objeto terra de cultivos
capa_terra <- rast(ARCHIVO_RASTER_CULTIVOS)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- capa_terra

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 2 PIÑA
# Objeto terra de piña
capa_terra <- rast(ARCHIVO_RASTER_PINA)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 3 PALMA
# Objeto terra de palma
capa_terra <- rast(ARCHIVO_RASTER_PALMA)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 4 PASTOS
# Objeto terra de palma
capa_terra <- rast(ARCHIVO_RASTER_PASTOS)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 5 CAFÉ
# Objeto terra de café
capa_terra <- rast(ARCHIVO_RASTER_CAFE)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 6 BANANO
# Objeto terra de banano
capa_terra <- rast(ARCHIVO_RASTER_BANANO)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 7 CAÑA
# Objeto terra de caña
capa_terra <- rast(ARCHIVO_RASTER_CANA_2020)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 8 COBERTURA FORESTAL
# Objeto terra de cobertura forestal
capa_terra <- rast(ARCHIVO_RASTER_COBERTURA_FORESTAL)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 9 PATRIMO NATURAL DEL ESTADO (PNE)
# Objeto terra de PNE
capa_terra <- rast(ARCHIVO_RASTER_PNE)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 10 REGISTRO NACIONAL DE HUMEDALES (RNH)
# Objeto terra de RNH
capa_terra <- rast(ARCHIVO_RASTER_RNH)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()


# 11 ÁREAS SILVESTRES PROTEGIDAS (ASP)
# Objeto terra de ASP
capa_terra <- rast(ARCHIVO_RASTER_ASP)

# Adición a la caoa de uso agropecuario y bosques
agropecuario_bosques_terra <- merge(capa_terra, agropecuario_bosques_terra, overwrite=TRUE)

# Borrado de objetos innecesarios
rm(capa_terra)
gc()
```


# Almacenamiento de la capa de uso agropecuario y bosques

```{r}
#| label: almacenamiento-capa-uso-agropecuario-bosques
#| code-fold: show
#| code-summary: "Código para el almacenamiento de la capa de uso agropecuario y bosques"


agropecuario_bosques_terra |> writeRaster(
  ARCHIVO_RASTER_USO_AGROPECUARIO_BOSQUES,
  overwrite=TRUE
)
```
