project:
  type: book
  output-dir: docs

book:
  title: "Mapa de uso agropecuario y bosques de Costa Rica para el año 2020"
  chapters:
    - index.qmd

format:
  html:
    lang: es
    theme: cosmo
    toc-expand: 5